plugins {
    id 'com.android.application' version '8.5.2'
}

android {
    namespace 'com.fliprush7.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.fliprush7.app'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['.']
            java.include 'MainActivity.java'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
